# Generated by Django 4.2.6 on 2023-10-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('davlat', models.CharField(blank=True, max_length=50, null=True)),
                ('jins', models.CharField(blank=True, choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=5, null=True)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('davomiylik', models.CharField(max_length=40)),
                ('narx', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('janr', models.CharField(blank=True, max_length=20, null=True)),
                ('yil', models.PositiveIntegerField(blank=True, null=True)),
                ('aktyorlar', models.ManyToManyField(to='film.aktyor')),
            ],
        ),
    ]
